/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Formularios;

/**
 *
 * @author Emmanuelito18
 */
import clases.conectarBase;
import java.awt.Toolkit;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class crearGrupo extends javax.swing.JInternalFrame {

    /**
     * Creates new form crearGrupo
     */
    conectarBase conexion=null;
    PreparedStatement ps=null;
    //ResultSet rs=null;
    String sTurno=null;
    String idc;
    int fila=0;
   
    DefaultTableModel modelo=new DefaultTableModel(){
    public boolean isCellEditable(int row,int column){
        return false;
    }
    };
    
    public crearGrupo() {
        initComponents();
        btn_editarAlumno.setEnabled(false);
        conexion=new conectarBase();
        modelo.addColumn("Grupo");
        modelo.addColumn("Turno");
        modelo.addColumn("Número lista");
        modelo.addColumn("Boleta");
        modelo.addColumn("Apellido paterno");
        modelo.addColumn("Apellido materno");
        modelo.addColumn("Nombre");
        modelo.addColumn("Correo");
        this.tb_alumnos.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lbl_titulo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lbl_apellidoPaterno = new javax.swing.JLabel();
        txt_apellidoPaterno = new javax.swing.JTextField();
        txt_apellidoMaterno = new javax.swing.JTextField();
        lbl_apellidoMaterno = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        lbl_nombre = new javax.swing.JLabel();
        txt_boleta = new javax.swing.JTextField();
        lbl_boleta = new javax.swing.JLabel();
        txt_numeroLista = new javax.swing.JTextField();
        lbl_numeroLista = new javax.swing.JLabel();
        btn_guardarAlumno = new javax.swing.JButton();
        btn_guardarGrupo = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();
        txt_correo = new javax.swing.JTextField();
        lbl_correo = new javax.swing.JLabel();
        btn_editarAlumno = new javax.swing.JButton();
        lbl_avisoApellidoPaterno = new javax.swing.JLabel();
        lbl_avisoApellidoMaterno = new javax.swing.JLabel();
        lbl_avisoNombre = new javax.swing.JLabel();
        lbl_avisoBoleta = new javax.swing.JLabel();
        lbl_avisoNumeroLista = new javax.swing.JLabel();
        lbl_avisoCorreo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txt_grupo = new javax.swing.JTextField();
        lbl_turno = new javax.swing.JLabel();
        rbtn_matutino = new javax.swing.JRadioButton();
        rbtn_vespertino = new javax.swing.JRadioButton();
        lbl_avisoGrupo = new javax.swing.JLabel();
        lbl_avisoTurno = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_alumnos = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        lbl_titulo.setFont(new java.awt.Font("Lucida Handwriting", 0, 18)); // NOI18N
        lbl_titulo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_titulo.setText("Crear grupo");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Alumno", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Handwriting", 0, 12))); // NOI18N

        lbl_apellidoPaterno.setFont(new java.awt.Font("Lucida Handwriting", 0, 12)); // NOI18N
        lbl_apellidoPaterno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_apellidoPaterno.setText("Apellido paterno");

        txt_apellidoPaterno.setFont(new java.awt.Font("Lucida Handwriting", 0, 12)); // NOI18N
        txt_apellidoPaterno.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_apellidoPaterno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_apellidoPaternoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_apellidoPaternoKeyTyped(evt);
            }
        });

        txt_apellidoMaterno.setFont(new java.awt.Font("Lucida Handwriting", 0, 12)); // NOI18N
        txt_apellidoMaterno.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_apellidoMaterno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_apellidoMaternoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_apellidoMaternoKeyTyped(evt);
            }
        });

        lbl_apellidoMaterno.setFont(new java.awt.Font("Lucida Handwriting", 0, 12)); // NOI18N
        lbl_apellidoMaterno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_apellidoMaterno.setText("Apellido materno");

        txt_nombre.setFont(new java.awt.Font("Lucida Handwriting", 0, 12)); // NOI18N
        txt_nombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_nombreKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_nombreKeyTyped(evt);
            }
        });

        lbl_nombre.setFont(new java.awt.Font("Lucida Handwriting", 0, 12)); // NOI18N
        lbl_nombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_nombre.setText("Nombre");

        txt_boleta.setFont(new java.awt.Font("Lucida Handwriting", 0, 12)); // NOI18N
        txt_boleta.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_boleta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_boletaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_boletaKeyTyped(evt);
            }
        });

        lbl_boleta.setFont(new java.awt.Font("Lucida Handwriting", 0, 12)); // NOI18N
        lbl_boleta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_boleta.setText("Boleta");

        txt_numeroLista.setFont(new java.awt.Font("Lucida Handwriting", 0, 12)); // NOI18N
        txt_numeroLista.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_numeroLista.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_numeroListaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_numeroListaKeyTyped(evt);
            }
        });

        lbl_numeroLista.setFont(new java.awt.Font("Lucida Handwriting", 0, 12)); // NOI18N
        lbl_numeroLista.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_numeroLista.setText("Número de lista");

        btn_guardarAlumno.setFont(new java.awt.Font("Lucida Handwriting", 0, 12)); // NOI18N
        btn_guardarAlumno.setText("Guardar alumno");
        btn_guardarAlumno.setEnabled(false);
        btn_guardarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarAlumnoActionPerformed(evt);
            }
        });

        btn_guardarGrupo.setFont(new java.awt.Font("Lucida Handwriting", 0, 12)); // NOI18N
        btn_guardarGrupo.setText("Guardar grupo completo");
        btn_guardarGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarGrupoActionPerformed(evt);
            }
        });

        btn_cancelar.setFont(new java.awt.Font("Lucida Handwriting", 0, 12)); // NOI18N
        btn_cancelar.setText("Cancelar");
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });

        txt_correo.setFont(new java.awt.Font("Lucida Handwriting", 0, 12)); // NOI18N
        txt_correo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_correo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_correoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_correoKeyTyped(evt);
            }
        });

        lbl_correo.setFont(new java.awt.Font("Lucida Handwriting", 0, 12)); // NOI18N
        lbl_correo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_correo.setText("Correo electrónico (opcional)");

        btn_editarAlumno.setFont(new java.awt.Font("Lucida Handwriting", 0, 12)); // NOI18N
        btn_editarAlumno.setText("Editar alumno");
        btn_editarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarAlumnoActionPerformed(evt);
            }
        });

        lbl_avisoApellidoPaterno.setFont(new java.awt.Font("Lucida Handwriting", 0, 12)); // NOI18N
        lbl_avisoApellidoPaterno.setForeground(new java.awt.Color(255, 0, 0));
        lbl_avisoApellidoPaterno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_avisoApellidoPaterno.setText("*Campo obligatorio");

        lbl_avisoApellidoMaterno.setFont(new java.awt.Font("Lucida Handwriting", 0, 12)); // NOI18N
        lbl_avisoApellidoMaterno.setForeground(new java.awt.Color(255, 0, 0));
        lbl_avisoApellidoMaterno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_avisoApellidoMaterno.setText("*Campo obligatorio");

        lbl_avisoNombre.setFont(new java.awt.Font("Lucida Handwriting", 0, 12)); // NOI18N
        lbl_avisoNombre.setForeground(new java.awt.Color(255, 0, 0));
        lbl_avisoNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_avisoNombre.setText("*Campo obligatorio");

        lbl_avisoBoleta.setFont(new java.awt.Font("Lucida Handwriting", 0, 12)); // NOI18N
        lbl_avisoBoleta.setForeground(new java.awt.Color(255, 0, 0));
        lbl_avisoBoleta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_avisoBoleta.setText("*Campo obligatorio");

        lbl_avisoNumeroLista.setFont(new java.awt.Font("Lucida Handwriting", 0, 12)); // NOI18N
        lbl_avisoNumeroLista.setForeground(new java.awt.Color(255, 0, 0));
        lbl_avisoNumeroLista.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_avisoNumeroLista.setText("*Campo obligatorio");

        lbl_avisoCorreo.setFont(new java.awt.Font("Lucida Handwriting", 0, 12)); // NOI18N
        lbl_avisoCorreo.setForeground(new java.awt.Color(255, 0, 0));
        lbl_avisoCorreo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_apellidoPaterno)
                            .addComponent(lbl_apellidoPaterno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_avisoApellidoPaterno, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_apellidoMaterno)
                            .addComponent(lbl_apellidoMaterno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_avisoApellidoMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(78, 78, 78)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_nombre)
                            .addComponent(lbl_nombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_avisoNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btn_guardarAlumno)
                                .addGap(18, 18, 18)
                                .addComponent(btn_guardarGrupo)
                                .addGap(18, 18, 18)
                                .addComponent(btn_editarAlumno)
                                .addGap(18, 18, 18)
                                .addComponent(btn_cancelar))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txt_boleta)
                                        .addComponent(lbl_boleta, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lbl_avisoBoleta))
                                .addGap(40, 40, 40)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_numeroLista, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_numeroLista, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_avisoNumeroLista))
                                .addGap(32, 32, 32)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_correo)
                                    .addComponent(lbl_correo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbl_avisoCorreo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(14, 14, 14)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lbl_apellidoPaterno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_apellidoPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lbl_nombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lbl_apellidoMaterno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_apellidoMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_avisoApellidoPaterno)
                    .addComponent(lbl_avisoApellidoMaterno)
                    .addComponent(lbl_avisoNombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(lbl_boleta)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txt_boleta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(txt_correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lbl_numeroLista)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_numeroLista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbl_correo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_avisoBoleta)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_avisoNumeroLista)
                        .addComponent(lbl_avisoCorreo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_guardarAlumno)
                    .addComponent(btn_guardarGrupo)
                    .addComponent(btn_editarAlumno)
                    .addComponent(btn_cancelar))
                .addGap(14, 14, 14))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Grupo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Handwriting", 0, 12))); // NOI18N

        txt_grupo.setFont(new java.awt.Font("Lucida Handwriting", 0, 12)); // NOI18N
        txt_grupo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_grupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_grupoActionPerformed(evt);
            }
        });
        txt_grupo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_grupoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_grupoKeyTyped(evt);
            }
        });

        lbl_turno.setFont(new java.awt.Font("Lucida Handwriting", 0, 12)); // NOI18N
        lbl_turno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_turno.setText("Turno:");

        buttonGroup1.add(rbtn_matutino);
        rbtn_matutino.setFont(new java.awt.Font("Lucida Handwriting", 0, 12)); // NOI18N
        rbtn_matutino.setText("Matutino");
        rbtn_matutino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_matutinoActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtn_vespertino);
        rbtn_vespertino.setFont(new java.awt.Font("Lucida Handwriting", 0, 12)); // NOI18N
        rbtn_vespertino.setText("Vespertino");
        rbtn_vespertino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_vespertinoActionPerformed(evt);
            }
        });

        lbl_avisoGrupo.setFont(new java.awt.Font("Lucida Handwriting", 0, 12)); // NOI18N
        lbl_avisoGrupo.setForeground(new java.awt.Color(255, 0, 0));
        lbl_avisoGrupo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_avisoGrupo.setText("*Campo obligatorio");

        lbl_avisoTurno.setFont(new java.awt.Font("Lucida Handwriting", 0, 12)); // NOI18N
        lbl_avisoTurno.setForeground(new java.awt.Color(255, 0, 0));
        lbl_avisoTurno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_avisoTurno.setText("*Campo obligatorio");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_turno)
                            .addComponent(txt_grupo, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_avisoGrupo)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(rbtn_matutino)
                                .addGap(18, 18, 18)
                                .addComponent(rbtn_vespertino)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(lbl_avisoTurno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_grupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_avisoGrupo)
                .addGap(8, 8, 8)
                .addComponent(lbl_turno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtn_matutino)
                    .addComponent(rbtn_vespertino))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_avisoTurno)
                .addContainerGap())
        );

        tb_alumnos.setFont(new java.awt.Font("Lucida Handwriting", 0, 12)); // NOI18N
        tb_alumnos.setModel(modelo);
        tb_alumnos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_alumnosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tb_alumnos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(lbl_titulo))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(lbl_titulo)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /*private void llenarCombo(){
        try{
            String consulta="SELECT codigo_marca,nombre_marca FROM marcas";
            PreparedStatement comando=(PreparedStatement)conexion.conectar.prepareStatement(consulta);
            markas=comando.executeQuery();
            while(markas.next()){
                cmbMarca.addItem(markas.getString(2));
            }
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(rootPane,"Error al consultar las marcas de los artículos"+e);
        }
    }*/
    private void btn_guardarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarAlumnoActionPerformed
        // TODO add your handling code here:
        /*guardarAlumno();
        limpiarCampos();*/
        String []info=new String[9];
        info[0]=txt_grupo.getText();
        info[1]=sTurno;
        info[2]=txt_numeroLista.getText();
        info[3]=txt_boleta.getText();
        info[4]=txt_apellidoPaterno.getText();
        info[5]=txt_apellidoMaterno.getText();
        info[6]=txt_nombre.getText();
        info[7]=txt_correo.getText();
        modelo.addRow(info);
        limpiarCampos();
                
    }//GEN-LAST:event_btn_guardarAlumnoActionPerformed

    private void btn_guardarGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarGrupoActionPerformed
        // TODO add your handling code here:
        /*Primero Guarda el Grupo con su respectivo turno*/
        int Turno;
        String Grupo;
        Grupo=txt_grupo.getText();
        Turno=Integer.parseInt(sTurno);
         try{    
                    ps=conexion.conectar.prepareStatement("INSERT INTO grupos (codigo_grupo,turno) VALUES (?,?)");
                   
                    ps.setString(1,Grupo);//grupo
                    ps.setInt(2,Turno);//turno
                    ps.executeUpdate();
                    JOptionPane.showMessageDialog(rootPane,"Grupo guardado con éxito");
                    limpiarCampos1();
                }
                catch(SQLException e){
                    JOptionPane.showMessageDialog(rootPane,"Error al guardar el artículo, verifique...");
                }
         /*Luego guarda a los alumnos en el grupo con su respectivo turno*/
        int turno,lista,boleta;        
        if(tb_alumnos.getRowCount()>0){
            for(int i=0;i<tb_alumnos.getRowCount();i++){
                if(tb_alumnos.getValueAt(i,7)==null){            
                try{    
                    ps=conexion.conectar.prepareStatement("INSERT INTO alumnos (codigo_grupo,turno,numero_lista,"
                        + "boleta,apellido_paterno,apellido_materno,nombre) VALUES (?,?,?,?,?,?,?)");
                   
                    ps.setString(1,(String)tb_alumnos.getValueAt(i,0));//grupo
                    ps.setInt(2,turno=Integer.parseInt(tb_alumnos.getValueAt(i,1).toString()));//turno
                    ps.setInt(3,lista=Integer.parseInt(tb_alumnos.getValueAt(i,2).toString()));//lista
                    ps.setInt(4,boleta=Integer.parseInt(tb_alumnos.getValueAt(i,3).toString()));//boleta
                    ps.setString(5,(String)tb_alumnos.getValueAt(i,4));//ap paterno
                    ps.setString(6,(String)tb_alumnos.getValueAt(i,5));//ap materno
                    ps.setString(7,(String)tb_alumnos.getValueAt(i,6));//nombre
                    //ps.setString(7,(String)tb_alumnos.getValueAt(i,7));//correo
                    ps.executeUpdate();
                    JOptionPane.showMessageDialog(rootPane,"Grupo guardado con éxito");
                    limpiarCampos1();
                }
                catch(SQLException e){
                    JOptionPane.showMessageDialog(rootPane,"Error al guardar el artículo, verifique...");
                }
            }else{
             try{
                                
                    ps=conexion.conectar.prepareStatement("INSERT INTO alumnos (codigo_grupo,turno,numero_lista,"
                        + "boleta,apellido_paterno,apellido_materno,nombre,correo) VALUES (?,?,?,?,?,?,?,?)");
                   
                    ps.setString(1,(String)tb_alumnos.getValueAt(i,0));//grupo
                    ps.setInt(2,turno=Integer.parseInt(tb_alumnos.getValueAt(i,1).toString()));//turno
                    ps.setInt(3,lista=Integer.parseInt(tb_alumnos.getValueAt(i,2).toString()));//lista
                    ps.setInt(4,boleta=Integer.parseInt(tb_alumnos.getValueAt(i,3).toString()));//boleta
                    ps.setString(5,(String)tb_alumnos.getValueAt(i,4));//ap paterno
                    ps.setString(6,(String)tb_alumnos.getValueAt(i,5));//ap materno
                    ps.setString(7,(String)tb_alumnos.getValueAt(i,6));//nombre
                    ps.setString(8,(String)tb_alumnos.getValueAt(i,7));//correo
                    ps.executeUpdate();
                    JOptionPane.showMessageDialog(rootPane,"Grupo guardado con éxito");
                    limpiarCampos1();
                }
                catch(SQLException e){
                    JOptionPane.showMessageDialog(rootPane,"Error al guardar el artículo, verifique...");
                }   
            }
        }
        }
        else{
            JOptionPane.showMessageDialog(null,"La tabla está vacía");
        }
    }//GEN-LAST:event_btn_guardarGrupoActionPerformed

    private void rbtn_matutinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn_matutinoActionPerformed
        // TODO add your handling code here:
        sTurno="0";
        validarCamposVacios();
        habilitarBoton();
    }//GEN-LAST:event_rbtn_matutinoActionPerformed

    private void rbtn_vespertinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn_vespertinoActionPerformed
        // TODO add your handling code here:
        sTurno="1";
        validarCamposVacios();
        habilitarBoton();
    }//GEN-LAST:event_rbtn_vespertinoActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        // TODO add your handling code here:
        int res=JOptionPane.showConfirmDialog(rootPane,"¿Quieres salir?\nNo se guardarán los datos no guardados","Advertencia",JOptionPane.YES_NO_OPTION,JOptionPane.WARNING_MESSAGE);
        //this.dispose();
        if(res==JOptionPane.YES_OPTION){
            this.dispose();
        }
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void btn_editarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarAlumnoActionPerformed
        // TODO add your handling code here:
        if(fila==-1){
            JOptionPane.showMessageDialog(null,"No se seleccionó una fila");
        }
        else{
            //idc=(String)tb_alumnos.getValueAt(fila,0).toString();
            String Grupo=(String)tb_alumnos.getValueAt(fila,0).toString();
            String Turno=(String)tb_alumnos.getValueAt(fila,1).toString();
            String NumeroLista=(String)tb_alumnos.getValueAt(fila,2).toString();
            String Boleta=(String)tb_alumnos.getValueAt(fila,3).toString();
            String ApellidoPaterno=(String)tb_alumnos.getValueAt(fila,4).toString();
            String ApellidoMaterno=(String)tb_alumnos.getValueAt(fila,5).toString();
            String Nombre=(String)tb_alumnos.getValueAt(fila,6).toString();
            String Correo=(String)tb_alumnos.getValueAt(fila,7).toString();
            
            //txt_grupo.setText(""+idc);
            txt_grupo.setText(Grupo);
            txt_numeroLista.setText(NumeroLista);
            txt_boleta.setText(Boleta);
            txt_apellidoPaterno.setText(ApellidoPaterno);
            txt_apellidoMaterno.setText(ApellidoMaterno);
            txt_nombre.setText(Nombre);
            txt_correo.setText(Correo);
            
            modelo.removeRow(fila);
        }
        btn_guardarAlumno.setEnabled(true);
        btn_editarAlumno.setEnabled(false);
    }//GEN-LAST:event_btn_editarAlumnoActionPerformed

    private void txt_grupoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_grupoKeyTyped
        // TODO add your handling code here:
        validacionGrupo(evt);
        if(txt_grupo.getText().length()>=5){
            /*Comprueba si el texto de txt_grupo es mayor o igual a 5*/
            evt.consume();
            /*termina el evento para que no vuelva a ocurrir*/
            Toolkit.getDefaultToolkit().beep();
            /*Emite un pitido de error*/
            JOptionPane.showMessageDialog(null,"Solo se permiten 5 caracteres como máximo","Error", HEIGHT);
            /*Muestra el aviso al usuario*/
        }
    }//GEN-LAST:event_txt_grupoKeyTyped

    private void txt_apellidoPaternoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_apellidoPaternoKeyTyped
        // TODO add your handling code here:
        validacionCaracteres(evt);
        if(txt_apellidoPaterno.getText().length()>=30){
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(null,"Solo se permiten 30 caracteres como máximo","Error", HEIGHT);
        }
    }//GEN-LAST:event_txt_apellidoPaternoKeyTyped

    private void txt_apellidoMaternoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_apellidoMaternoKeyTyped
        // TODO add your handling code here:
        validacionCaracteres(evt);
        if(txt_apellidoMaterno.getText().length()>=30){
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(null,"Solo se permiten 30 caracteres como máximo","Error", HEIGHT);
        }
    }//GEN-LAST:event_txt_apellidoMaternoKeyTyped

    private void txt_nombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nombreKeyTyped
        // TODO add your handling code here:
        validacionCaracteres(evt);
        if(txt_nombre.getText().length()>=35){
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(null,"Solo se permiten 35 caracteres como máximo","Error", HEIGHT);
        }
    }//GEN-LAST:event_txt_nombreKeyTyped

    private void txt_boletaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_boletaKeyTyped
        // TODO add your handling code here:
        validacionCaractersBoleta(evt);
        if(txt_boleta.getText().length()>=10){
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(null,"Solo se permiten 10 caracteres como máximo","Error", HEIGHT);
        }
    }//GEN-LAST:event_txt_boletaKeyTyped

    private void txt_numeroListaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_numeroListaKeyTyped
        // TODO add your handling code here:
        validacionCaractersBoleta(evt);
        if(txt_numeroLista.getText().length()>=2){
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(null,"Solo se permiten 2 caracteres como máximo","Error", HEIGHT);
        }
    }//GEN-LAST:event_txt_numeroListaKeyTyped

    private void txt_correoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_correoKeyTyped
        // TODO add your handling code here:
        validarCorreo(evt);
        if(txt_correo.getText().length()>=40){
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(null,"Solo se permiten 40 caracteres como máximo","Error", HEIGHT);
        }
    }//GEN-LAST:event_txt_correoKeyTyped

    private void txt_grupoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_grupoKeyReleased
        // TODO add your handling code here:
        validarCamposVacios();
        habilitarBoton();
    }//GEN-LAST:event_txt_grupoKeyReleased

    private void txt_grupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_grupoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_grupoActionPerformed

    private void txt_apellidoPaternoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_apellidoPaternoKeyReleased
        // TODO add your handling code here:
        validarCamposVacios();
        habilitarBoton();
    }//GEN-LAST:event_txt_apellidoPaternoKeyReleased

    private void txt_apellidoMaternoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_apellidoMaternoKeyReleased
        // TODO add your handling code here:
        validarCamposVacios();
        habilitarBoton();
    }//GEN-LAST:event_txt_apellidoMaternoKeyReleased

    private void txt_nombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nombreKeyReleased
        // TODO add your handling code here:
        habilitarBoton();
        validarCamposVacios();
    }//GEN-LAST:event_txt_nombreKeyReleased

    private void txt_boletaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_boletaKeyReleased
        // TODO add your handling code here:
        validarCamposVacios();
        habilitarBoton();
    }//GEN-LAST:event_txt_boletaKeyReleased

    private void txt_numeroListaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_numeroListaKeyReleased
        // TODO add your handling code here:
        validarCamposVacios();
        habilitarBoton();
    }//GEN-LAST:event_txt_numeroListaKeyReleased

    private void txt_correoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_correoKeyReleased
        // TODO add your handling code here:
        validarCamposVacios();
        habilitarBoton();
    }//GEN-LAST:event_txt_correoKeyReleased

    private void tb_alumnosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_alumnosMouseClicked
        // TODO add your handling code here:
        fila=tb_alumnos.getSelectedRow();
        btn_guardarAlumno.setEnabled(false);
        btn_editarAlumno.setEnabled(true);
    }//GEN-LAST:event_tb_alumnosMouseClicked
    
    private void limpiarCampos(){
        txt_apellidoPaterno.setText("");
        txt_apellidoMaterno.setText("");
        txt_nombre.setText("");
        txt_boleta.setText("");
        txt_numeroLista.setText("");
        txt_correo.setText("");
    }
    private void limpiarCampos1(){
        txt_grupo.setText("");
        txt_apellidoPaterno.setText("");
        txt_apellidoMaterno.setText("");
        txt_nombre.setText("");
        txt_boleta.setText("");
        txt_numeroLista.setText("");
        txt_correo.setText("");
        buttonGroup1.clearSelection();
    }
    private void guardarAlumno(){
        
        limpiarCampos();
    }
    
    /*Método que el tipo de caracteres*/
    /*Utiliza el código ASCII*/
    public void validacionCaracteres(java.awt.event.KeyEvent evento){
        if(evento.getKeyChar()>=33&&evento.getKeyChar()<=64
                ||evento.getKeyChar()>=91&&evento.getKeyChar()<=96
                ||evento.getKeyChar()>=123&&evento.getKeyChar()<=191
                ||evento.getKeyChar()==198||evento.getKeyChar()==208
                ||evento.getKeyChar()>=215&&evento.getKeyChar()<=216
                ||evento.getKeyChar()>=222&&evento.getKeyChar()<=223
                ||evento.getKeyChar()>=229&&evento.getKeyChar()<=230
                ||evento.getKeyChar()==240||evento.getKeyChar()>=247&&evento.getKeyChar()<=248
                ||evento.getKeyChar()>=254&&evento.getKeyChar()<=255){
            /*valida los caracteres ingresados*/
            /*para que se pueda poner espacios, pero no números ni caracteres*/
            evento.consume();
            /*para que el evento se consuma*/
            JOptionPane.showMessageDialog(this,"No se permiten caracteres especiales");
        }
        /*System.out.print("Soy la letra: "+evento.getKeyChar()+" y tengo el numero ASCII: ");
        System.out.println(evento.getKeyChar()+0);*/
    }
    /*valida si solo se ingresan números*/
    public void validacionCaractersBoleta(java.awt.event.KeyEvent evento){
        if(evento.getKeyChar()>=32&&evento.getKeyChar()<=47
                ||evento.getKeyChar()>=58&&evento.getKeyChar()<=255){
            evento.consume();
            JOptionPane.showMessageDialog(this,"Caracteres permitidos: (0-9)");
        }
    }
    /*Valida si solo son letras y  números*/
    public void validacionGrupo(java.awt.event.KeyEvent evento){
        if(evento.getKeyChar()>=32&&evento.getKeyChar()<=47
                ||evento.getKeyChar()>=58&&evento.getKeyChar()<=64
                ||evento.getKeyChar()>=91&&evento.getKeyChar()<=208
                ||evento.getKeyChar()>=210&&evento.getKeyChar()<=255){
            evento.consume();
            JOptionPane.showMessageDialog(this,"Caracteres permitidos: Números (0-9), letras (A-Z)");
        }
    }
    /*Para los campos vacíos*/
    public void validarCamposVacios(){
        if(txt_nombre.getText().isEmpty()){
            lbl_avisoNombre.setText("*Campo obligatorio");
        }
        else{
            lbl_avisoNombre.setText("");
        }
        
        if(txt_apellidoPaterno.getText().isEmpty()){
            lbl_avisoApellidoPaterno.setText("*Campo obligatorio");
        }
        else{
            lbl_avisoApellidoPaterno.setText("");
        }
        
        if(txt_apellidoMaterno.getText().isEmpty()){
            lbl_avisoApellidoMaterno.setText("*Campo obligatorio");
        }
        else{
            lbl_avisoApellidoMaterno.setText("");
        }
        
        /*if(txt_correo.getText().isEmpty()){
            lbl_avisoCorreo.setText("Campo opcional");
        }
        else{*/
            if(!txt_correo.getText().contains("@")
                ||!txt_correo.getText().contains(".")&& !txt_correo.getText().isEmpty()){//para comparar si tiene @ y .
                lbl_avisoCorreo.setText("Correo NO válido");
            }
            else{
            lbl_avisoCorreo.setText("");            
        }
        
        //}
        
        if(txt_boleta.getText().isEmpty()){
            lbl_avisoBoleta.setText("*Campo obligatorio");
        }
        else{
            lbl_avisoBoleta.setText("");
        }
        
        if(txt_grupo.getText().isEmpty()){
         lbl_avisoGrupo.setText("*Campo obligatorio");
        }
        else{
            lbl_avisoGrupo.setText("");
        }
        
        if(txt_numeroLista.getText().isEmpty()){
            lbl_avisoNumeroLista.setText("*Campo obligatorio");
        }
        else{
            lbl_avisoNumeroLista.setText("");
        }
        
        
        if(rbtn_matutino.isSelected()||rbtn_vespertino.isSelected()){
            lbl_avisoTurno.setText("");
        }
        else{
            lbl_avisoTurno.setText("*Campo obligatorio");
        }
    }
    
    /*Validación del correo*/
    public void validarCorreo(java.awt.event.KeyEvent evento){
        if(evento.getKeyChar()>=32&&evento.getKeyChar()<=45/*No permite espacio hasta guíon*/
                ||evento.getKeyChar()==47/*No permite / */
                ||evento.getKeyChar()>=58&&evento.getKeyChar()<=63 /**/
                ||evento.getKeyChar()>=65&&evento.getKeyChar()<=94
                ||evento.getKeyChar()==96
                ||evento.getKeyChar()>=123&&evento.getKeyChar()<=255){
            /*Valida los caracteres ingresados*/
            evento.consume();
            JOptionPane.showMessageDialog(this,"No se permite ese caracter en específico");
        }
    }
    
    /*Habilita botón*/
    public void habilitarBoton(){
                
        if(!lbl_avisoGrupo.getText().isEmpty()||!lbl_avisoTurno.getText().isEmpty()
                ||!lbl_avisoApellidoPaterno.getText().isEmpty()||!lbl_avisoApellidoMaterno.getText().isEmpty()
                ||!lbl_avisoNombre.getText().isEmpty()||!lbl_avisoBoleta.getText().isEmpty()
                ||!lbl_avisoNumeroLista.getText().isEmpty()||!lbl_avisoCorreo.getText().isEmpty()){
            btn_guardarAlumno.setEnabled(false);
        }
        else{
            btn_guardarAlumno.setEnabled(true);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_editarAlumno;
    private javax.swing.JButton btn_guardarAlumno;
    private javax.swing.JButton btn_guardarGrupo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_apellidoMaterno;
    private javax.swing.JLabel lbl_apellidoPaterno;
    private javax.swing.JLabel lbl_avisoApellidoMaterno;
    private javax.swing.JLabel lbl_avisoApellidoPaterno;
    private javax.swing.JLabel lbl_avisoBoleta;
    private javax.swing.JLabel lbl_avisoCorreo;
    private javax.swing.JLabel lbl_avisoGrupo;
    private javax.swing.JLabel lbl_avisoNombre;
    private javax.swing.JLabel lbl_avisoNumeroLista;
    private javax.swing.JLabel lbl_avisoTurno;
    private javax.swing.JLabel lbl_boleta;
    private javax.swing.JLabel lbl_correo;
    private javax.swing.JLabel lbl_nombre;
    private javax.swing.JLabel lbl_numeroLista;
    private javax.swing.JLabel lbl_titulo;
    private javax.swing.JLabel lbl_turno;
    private javax.swing.JRadioButton rbtn_matutino;
    private javax.swing.JRadioButton rbtn_vespertino;
    private javax.swing.JTable tb_alumnos;
    private javax.swing.JTextField txt_apellidoMaterno;
    private javax.swing.JTextField txt_apellidoPaterno;
    private javax.swing.JTextField txt_boleta;
    private javax.swing.JTextField txt_correo;
    private javax.swing.JTextField txt_grupo;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_numeroLista;
    // End of variables declaration//GEN-END:variables
}
