package Formularios;

//<editor-fold defaultstate="collapsed" desc="Librerias necesarias para la splash screen">
import clases.conectarBase;
import clases.notificacionesDS;
import clases.notificacionesJava;
import clases.poneImagenes;
import clases.verificaConexionInternet;
import java.awt.Color;//para crear colores personalizados
import java.awt.Point;//para obtener coordenadas en el programa
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;
//</editor-fold>

/**
 * Esta clase muestra un slpash screen 
 * @author Emmanuelito18
 */
public class splashScreen extends javax.swing.JFrame {
    private Color transparente;//Crea un color llamado transparente
    private Point punto;//se utliza para obtener el punto en que se está haciendo click y en donde está el mouse
    private Timer timer;//Se utiliza para que la barra de progreso aumente el procentaje
    
    //<editor-fold defaultstate="collapsed" desc="referencias de clases a cargar">
    private poneImagenes ponerImagenes;
    private notificacionesDS notificacionDS;
    private notificacionesJava notificacionJava;
    private inicioSesion iniciarSesion;
    private menu menuPrincipal;
    private crearGrupo creaGrupo;
    private editarGrupo editaGrupo;
    private generarGrupo generaGrupo;
    private mostrarGrupo muestraGrupo;
    private recuperarCuenta recuperaCuenta;
    private registrarCuenta registraCuenta;
    private verificaConexionInternet verificaConexion;
    private conectarBase conectaBaseDatos;
    //</editor-fold>
    /**
     * Creates new form splashScreen
     */
    public splashScreen() {
        initComponents();
        transparente=new Color(0,0,0,0);//Establece el color transparente al objeto transparente de la clase Color
        setLocationRelativeTo(null);
        setBackground(transparente);
        
        //<editor-fold defaultstate="collapsed" desc="Cambia el fondo del panel pnlFondo">
        poneImagenes fondo=new poneImagenes(pnl_Fondo, "/imagenes/shape2.png");
        pnl_Fondo.add(fondo).repaint();
        pnl_Fondo.setOpaque(false);
        pnl_Fondo.setBorder(null);
        pnl_Fondo.setBackground(transparente);
        //</editor-fold>
        barraProgresoIniciado();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_Fondo = new javax.swing.JPanel();
        lbl_logotipo = new javax.swing.JLabel();
        pb_barraCarga = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Splash screen");
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnl_Fondo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pnl_FondoMouseDragged(evt);
            }
        });
        pnl_Fondo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_FondoMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnl_FondoMousePressed(evt);
            }
        });

        lbl_logotipo.setFont(new java.awt.Font("Lucida Calligraphy", 0, 36)); // NOI18N
        lbl_logotipo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_logotipo.setText("Asistencia aleatoria");

        javax.swing.GroupLayout pnl_FondoLayout = new javax.swing.GroupLayout(pnl_Fondo);
        pnl_Fondo.setLayout(pnl_FondoLayout);
        pnl_FondoLayout.setHorizontalGroup(
            pnl_FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_logotipo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnl_FondoLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(pb_barraCarga, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_FondoLayout.setVerticalGroup(
            pnl_FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_FondoLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(lbl_logotipo)
                .addGap(104, 104, 104)
                .addComponent(pb_barraCarga, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(119, Short.MAX_VALUE))
        );

        getContentPane().add(pnl_Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Controla el progreso de la barra de carga y la carga de las demás clases del programa
     * @see <a href="https://youtu.be/Pq7fafeaQkw?si=CADfse2amhITfMrT" target="_blank"> Como hacer un progres barr que duncione correctamente</a> ver video para entender la forma en la que carga las clases
     * @see <a href="https://youtu.be/wIFvklD-dAc?si=qI7-fG3Ap-h5pD_P" target="_blank"> Como hacer un slpash screen en java</a> ver video para saber como funciona el slpash screen
     */
    private void barraProgresoIniciado(){
        timer=new Timer(45, (ActionEvent e) -> {//funcion lambda para el timer
           //<editor-fold defaultstate="collapsed" desc="Personalización barra de progreso">
           pb_barraCarga.setValue(pb_barraCarga.getValue()+1);//obtiene el valor que ya tiene y le suma 1
           pb_barraCarga.setBackground(Color.WHITE);//Cambia el color de fondo de la barra de progreso
           pb_barraCarga.setForeground(Color.ORANGE);//Cambia el color de la barra de progreso
           pb_barraCarga.setStringPainted(true);//Habilita el poder mostrar texto en la barra de prograso
           pb_barraCarga.setString("Cargando... "+pb_barraCarga.getValue()+"%");//Establece un texto en la barra de progreso
           //</editor-fold>
 
           //<editor-fold defaultstate="collapsed" desc="Carga en memoria las clases del programa">
            switch (pb_barraCarga.getValue()) {
                case 7:
                    ponerImagenes=new poneImagenes();
                    System.out.println("Se cargo la clase para poner imagenes");
                    break;
                case 14:
                    notificacionDS=new notificacionesDS();
                    System.out.println("Se cargaron las notificaciones DS");
                    break;
                case 21:
                    notificacionJava=new notificacionesJava();
                    System.out.println("Se cargaron las notificaciones java");
                    break;
                case 28:
                    iniciarSesion=new inicioSesion();
                    System.out.println("Se cargo el inicio de seción");
                    break;
                case 35:
                    menuPrincipal=new menu();
                    System.out.println("Se cargo el menú principal");
                    break;
                case 42:
                    creaGrupo=new crearGrupo();
                    System.out.println("Se cargo la creación de grupos");
                    break;
                case 49:
                    editaGrupo=new editarGrupo();
                    System.out.println("Se cargo la edición de grupos");
                    break;
                case 56:
                    generaGrupo=new generarGrupo();
                    System.out.println("Se cargo la generación de grupo");
                    break;
                case 63:
                    muestraGrupo=new mostrarGrupo();
                    System.out.println("Se cargo la muestra de grupos");
                    break;
                case 70:
                    recuperaCuenta=new recuperarCuenta();
                    System.out.println("Se cargo la recuperación de cuenta");
                    break;
                case 77:
                    registraCuenta=new registrarCuenta();
                    System.out.println("Se cargo el registro de cuenta");
                    break;
                case 84:
                    verificaConexion=new verificaConexionInternet();
                    System.out.println("Se cargo la verificacion de conexion a internet");
                    break;
                case 91:
                    conectaBaseDatos=new conectarBase();
                    System.out.println("Se cargo la conexion a la base de datos");
                    break;
                case 100:
                    System.out.println("He terminado de cargar todo");
                    timer.stop();//Detiene el timer
                    if (listener!=null) {//Notifica al listener que la carga está completa
                        listener.cargaCompleta();
                    }
            }
           //</editor-fold>
        });
        timer.start();//Inicia el timer
    }
    
    //<editor-fold defaultstate="collapsed" desc="Métodos para obtener las referencias a las clases cargadas en memoria">    
    /**
     * Este método obtiene la referencia de la clase {@code PoneImagenes}
     * @return La referencia a la clase {@code poneImagenes}
     */
    public poneImagenes getPoneImagenes(){
        return ponerImagenes;
    }
    
    /**
     * Este método obtiene la referencia de la clase {@code notificacionesDS}
     * @return La referencia a la clase {@code notificacionesDS}
     */
    public notificacionesDS getNotificacionesDS(){
        return notificacionDS;
    }
    
    /**
     * Este método obtiene la referencia de la clase {@code notificacionesJava}
     * @return La referencia a la clase {@code notificacionesJava}
     */
    public notificacionesJava getNotificacionesJava(){
        return notificacionJava;
    }
    
    /**
     * Este método obtiene la referencia de la clase {@code inicioSesion}
     * @return La referencia a la clase {@code inicioSesion}
     */
    public inicioSesion getInicioSesion(){
        return iniciarSesion;
    }
    
    /**
     * Este método obtiene la referencia de la clase {@code menu}
     * @return La referencia a la clase {@code menu}
     */
    public menu getMenu(){
        return menuPrincipal;
    }
    
    /**
     * Este método obtiene la referencia de la clase {@code crearGrupo}
     * @return La referencia a la clase {@code crearGrupo}
     */
    public crearGrupo getCrearGrupo(){
        return creaGrupo;
    }
    
    /**
     * Este método obtiene la referencia de la clase {@code editarGrupo}
     * @return La referencia a la clase {@code editarGrupo}
     */
    public editarGrupo getEditarGrupo(){
        return editaGrupo;
    }
    
    /**
     * Este método obtiene la referencia de la clase {@code generarGrupo}
     * @return La referencia a la clase {@code generarGrupo}
     */
    public generarGrupo getGenerarGrupo(){
        return generaGrupo;
    }
    
    /**
     * Este método obtiene la referencia de la clase {@code mostrarGrupo}
     * @return La referencia a la clase {@code mostrarGrupo}
     */
    public mostrarGrupo getMostrarGrupo(){
        return muestraGrupo;
    }
    
    /**
     * Este método obtiene la referencia de la clase {@code recuperarCuenta}
     * @return La referencia a la clase {@code recuperarCuenta}
     */
    public recuperarCuenta getRecuperarCuenta(){
        return recuperaCuenta;
    }
    
    /**
     * Este método obtiene la referencia de la clase {@code registrarcuenta}
     * @return La referencia a la clase {@code registrarCuenta}
     */
    public registrarCuenta getRegistrarCuenta(){
        return registraCuenta;
    }
    
    /**
     * Este método obtiene la referencia de la clase {@code verificaConexionInternet}
     * @return La referencia a la clase {@code verificaConexionInternet}
     */
    public verificaConexionInternet getVerificaConexionInternet(){
        return verificaConexion;
    }
    
    /**
     * Este método obtiene la referencia de la clase {@code conectarBase}
     * @return La referencia a la clase {@code conectarBase}
     */
    public conectarBase getConectarBase(){
        return conectaBaseDatos;
    }
    //</editor-fold>
    
    //<editor-fold defaultstate="collapsed" desc="callback para notificar que se terminó de cargar todas las clases del programa">
    public interface cargaCompletaListener{
        void cargaCompleta();
    }
    
    private cargaCompletaListener listener;//listener para el callback que sirve para avisar que termino de cargar todas las clases
    
    public void setCargaCompletaListener(cargaCompletaListener listener){
        this.listener=listener;
    }
    //</editor-fold>
    
    private void pnl_FondoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_FondoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_pnl_FondoMouseClicked

    /**
     * Se utiliza para obtener el punto del JFrame en la que se hace el click
     * @param evt 
     */
    private void pnl_FondoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_FondoMousePressed
        punto=evt.getPoint();//obtiene la posicion del mouse
        getComponentAt(punto);//obtine el componene en la posición punto (posición del mouse)
    }//GEN-LAST:event_pnl_FondoMousePressed

    /**
     * Se utiliza para saber la posición del mouse mientras se mueve teniendo el click izquierdo presionado
     * @param evt 
     */
    private void pnl_FondoMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_FondoMouseDragged
        // <editor-fold defaultstate="collapsed" desc="Obtiene la posición actual en donde se encuentra el cursor">
        int ActualX=this.getLocation().x;
        int ActualY=this.getLocation().y;
        // </editor-fold>
        
        // <editor-fold defaultstate="collapsed" desc="Calcula el movimieno del mouse">
        int movimientoX=(ActualX+evt.getX())-(ActualX+punto.x);
        int movimientoY=(ActualY+evt.getY())-(ActualY+punto.y);
        /*
        ActualX y ActualY sirven para obtner las coordenadas de la ventana o componente
        evt.getX() y evt.getY() sirven para obener las coordenadas de la posición del mouse
        punto.x y punto.y son las coordenas del mouse almacenadas previamente al hacer click
        Al restarse estas cantidades se obtiene el movimiento en cada eje
        */
        // </editor-fold>
        
        // <editor-fold defaultstate="collapsed" desc="Calcula la nueva ubicación del JFrame">
        int x=ActualX+movimientoX;
        int y=ActualY+movimientoY;
        //calcula la nueva posición sumando la posición actual de cada eje con el movimiento en cada eje
        // </editor-fold>
        
        this.setLocation(x,y);//establece la ubicación del JFrame según las coordenadas calculadas
    }//GEN-LAST:event_pnl_FondoMouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        //Esta clase debe cumplir con cargar el resto de las clases en memoria
        if(!verificaConexionInternet.verificarConexionGoogle()){//ESto necesita ser eliminado de esta clase
            /*
            1. Solicitar inicio de sesión del usuario
            2. Verificar si la base de datos local está vacia
            3. Si está vacia hacer la conexion a la base de datos MySQL y llenar la base de datos local
            4. Verificar la última actualizacion a la base de datos MySQL, tiene que ser menor a una semana
            si es mayor a una semana
            5. Si la última conexion es mayor a una semana, obtener todos los datos de la base de datos y meterlos en la base de daos locar
            6. Cerrar conexión a la base de datos MySQL
            7. Iniciar programa
            8. Utilizar la base de datos local
            */
            System.out.println("Hay conexion a internet");
        }else{
            /*
            1. Indicar al usuario que no posee conexion a internet
            2. Solicitar inicio de sesión del usuario
            3. Verificar si la base local está vacia
            4. Si está vacia, recordarle al usuario que necesita revisar la conexion a internet
            5. Verificar la última conexion a la base de datos MySQL
            6. Si es mayor a una semana, recordarle al usuario que necesita revisar la conexion
            a internet para actualizar la base de datos local
            7. Iniciar programa
            8. Utilizar base de datos local
            */
            System.out.println("Error de conexión\nNo se ha podido conectar a internet, por favor verifique su conexión a internet");
        }
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new splashScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbl_logotipo;
    private javax.swing.JProgressBar pb_barraCarga;
    private javax.swing.JPanel pnl_Fondo;
    // End of variables declaration//GEN-END:variables
}
