package Formularios;

//<editor-fold defaultstate="collapsed" desc="Librerias necesarias para la splash screen">
import clases.poneImagenes;
import java.awt.Color;//para crear colores personalizados
import java.awt.Point;//para obtener coordenadas en el programa
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
//</editor-fold>

/**
 * Esta clase muestra un slpash screen 
 * @author Emmanuelito18
 */
public class splashScreen extends javax.swing.JFrame {
    private Color transparente;//Crea un color llamado transparente
    private Point punto;//se utliza para obtener el punto en que se está haciendo click y en donde está el mouse
    /**
     * Creates new form splashScreen
     */
    public splashScreen() {
        initComponents();
        transparente=new Color(0,0,0,0);//Establece el color transparente al objeto transparente de la clase Color
        setLocationRelativeTo(null);
        setBackground(transparente);
        
        //<editor-fold defaultstate="collapsed" desc="Cambia el fondo del panel pnlFondo">
        poneImagenes fondo=new poneImagenes(pnlFondo, "/imagenes/Logotipo.png");
        pnlFondo.add(fondo).repaint();
        pnlFondo.setOpaque(false);
        pnlFondo.setBorder(null);
        pnlFondo.setBackground(transparente);
        //</editor-fold>
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFondo = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Splash screen");
        setUndecorated(true);

        pnlFondo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pnlFondoMouseDragged(evt);
            }
        });
        pnlFondo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlFondoMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlFondoMousePressed(evt);
            }
        });

        javax.swing.GroupLayout pnlFondoLayout = new javax.swing.GroupLayout(pnlFondo);
        pnlFondo.setLayout(pnlFondoLayout);
        pnlFondoLayout.setHorizontalGroup(
            pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 349, Short.MAX_VALUE)
        );
        pnlFondoLayout.setVerticalGroup(
            pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pnlFondoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlFondoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlFondoMouseClicked

    /**
     * Se utiliza para obtener el punto del JFrame en la que se hace el click
     * @param evt 
     */
    private void pnlFondoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlFondoMousePressed
        punto=evt.getPoint();//obtiene la posicion del mouse
        getComponentAt(punto);//obtine el componene en la posición punto (posición del mouse)
    }//GEN-LAST:event_pnlFondoMousePressed

    /**
     * Se utiliza para saber la posición del mouse mientras se mueve teniendo el click izquierdo presionado
     * @param evt 
     */
    private void pnlFondoMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlFondoMouseDragged
        // <editor-fold defaultstate="collapsed" desc="Obtiene la posición actual en donde se encuentra el cursor">
        int ActualX=this.getLocation().x;
        int ActualY=this.getLocation().y;
        // </editor-fold>
        
        // <editor-fold defaultstate="collapsed" desc="Calcula el movimieno del mouse">
        int movimientoX=(ActualX+evt.getX())-(ActualX+punto.x);
        int movimientoY=(ActualY+evt.getY())-(ActualY+punto.y);
        /*
        ActualX y ActualY sirven para obtner las coordenadas de la ventana o componente
        evt.getX() y evt.getY() sirven para obener las coordenadas de la posición del mouse
        punto.x y punto.y son las coordenas del mouse almacenadas previamente al hacer click
        Al restarse estas cantidades se obtiene el movimiento en cada eje
        */
        // </editor-fold>
        
        // <editor-fold defaultstate="collapsed" desc="Calcula la nueva ubicación del JFrame">
        int x=ActualX+movimientoX;
        int y=ActualY+movimientoY;
        //calcula la nueva posición sumando la posición actual de cada eje con el movimiento en cada eje
        // </editor-fold>
        
        this.setLocation(x,y);//establece la ubicación del JFrame según las coordenadas calculadas
    }//GEN-LAST:event_pnlFondoMouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new splashScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel pnlFondo;
    // End of variables declaration//GEN-END:variables
}
