package Formularios;

//<editor-fold defaultstate="collapsed" desc="Librerias necesarias para la splash screen">
import clases.poneImagenes;
import clases.verificaConexionInternet;
import java.awt.Color;//para crear colores personalizados
import java.awt.Point;//para obtener coordenadas en el programa
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;
//</editor-fold>

/**
 * Esta clase muestra un slpash screen 
 * @author Emmanuelito18
 */
public class splashScreen extends javax.swing.JFrame {
    private Color transparente;//Crea un color llamado transparente
    private Point punto;//se utliza para obtener el punto en que se está haciendo click y en donde está el mouse
    /**
     * Creates new form splashScreen
     */
    public splashScreen() {
        initComponents();
        transparente=new Color(0,0,0,0);//Establece el color transparente al objeto transparente de la clase Color
        setLocationRelativeTo(null);
        setBackground(transparente);
        
        //<editor-fold defaultstate="collapsed" desc="Cambia el fondo del panel pnlFondo">
        poneImagenes fondo=new poneImagenes(pnl_Fondo, "/imagenes/shape2.png");
        pnl_Fondo.add(fondo).repaint();
        pnl_Fondo.setOpaque(false);
        pnl_Fondo.setBorder(null);
        pnl_Fondo.setBackground(transparente);
        //</editor-fold>
        barraProgresoIniciado();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_Fondo = new javax.swing.JPanel();
        lbl_logotipo = new javax.swing.JLabel();
        pb_barraCarga = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Splash screen");
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnl_Fondo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pnl_FondoMouseDragged(evt);
            }
        });
        pnl_Fondo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_FondoMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnl_FondoMousePressed(evt);
            }
        });

        lbl_logotipo.setFont(new java.awt.Font("Lucida Calligraphy", 0, 36)); // NOI18N
        lbl_logotipo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_logotipo.setText("Asistencia aleatoria");

        javax.swing.GroupLayout pnl_FondoLayout = new javax.swing.GroupLayout(pnl_Fondo);
        pnl_Fondo.setLayout(pnl_FondoLayout);
        pnl_FondoLayout.setHorizontalGroup(
            pnl_FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_logotipo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnl_FondoLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(pb_barraCarga, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_FondoLayout.setVerticalGroup(
            pnl_FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_FondoLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(lbl_logotipo)
                .addGap(104, 104, 104)
                .addComponent(pb_barraCarga, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(119, Short.MAX_VALUE))
        );

        getContentPane().add(pnl_Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Controla el progreso de la barra de carga
     */
    private void barraProgresoIniciado(){
        Timer timer=new Timer(45, (ActionEvent e) -> {//funcion lambda para el timer
           pb_barraCarga.setValue(pb_barraCarga.getValue()+1);//obtiene el valor que ya tiene y le suma 1
           pb_barraCarga.setBackground(Color.WHITE);//Cambia el color de fondo de la barra de progreso
           pb_barraCarga.setForeground(Color.ORANGE);//Cambia el color de la barra de progreso
           pb_barraCarga.setStringPainted(true);//Habilita el poder mostrar texto en la barra de prograso
           pb_barraCarga.setString("Cargando... "+pb_barraCarga.getValue()+"%");//Establece un texto en la barra de progreso
        });
        timer.start();//inicia el timer
    }
    
    private void pnl_FondoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_FondoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_pnl_FondoMouseClicked

    /**
     * Se utiliza para obtener el punto del JFrame en la que se hace el click
     * @param evt 
     */
    private void pnl_FondoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_FondoMousePressed
        punto=evt.getPoint();//obtiene la posicion del mouse
        getComponentAt(punto);//obtine el componene en la posición punto (posición del mouse)
    }//GEN-LAST:event_pnl_FondoMousePressed

    /**
     * Se utiliza para saber la posición del mouse mientras se mueve teniendo el click izquierdo presionado
     * @param evt 
     */
    private void pnl_FondoMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_FondoMouseDragged
        // <editor-fold defaultstate="collapsed" desc="Obtiene la posición actual en donde se encuentra el cursor">
        int ActualX=this.getLocation().x;
        int ActualY=this.getLocation().y;
        // </editor-fold>
        
        // <editor-fold defaultstate="collapsed" desc="Calcula el movimieno del mouse">
        int movimientoX=(ActualX+evt.getX())-(ActualX+punto.x);
        int movimientoY=(ActualY+evt.getY())-(ActualY+punto.y);
        /*
        ActualX y ActualY sirven para obtner las coordenadas de la ventana o componente
        evt.getX() y evt.getY() sirven para obener las coordenadas de la posición del mouse
        punto.x y punto.y son las coordenas del mouse almacenadas previamente al hacer click
        Al restarse estas cantidades se obtiene el movimiento en cada eje
        */
        // </editor-fold>
        
        // <editor-fold defaultstate="collapsed" desc="Calcula la nueva ubicación del JFrame">
        int x=ActualX+movimientoX;
        int y=ActualY+movimientoY;
        //calcula la nueva posición sumando la posición actual de cada eje con el movimiento en cada eje
        // </editor-fold>
        
        this.setLocation(x,y);//establece la ubicación del JFrame según las coordenadas calculadas
    }//GEN-LAST:event_pnl_FondoMouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        //Esta clase debe cumplir con cargar el resto de las clases en memoria
        if(!verificaConexionInternet.verificarConexionGoogle()){//ESto necesita ser eliminado de esta clase
            /*
            1. Solicitar inicio de sesión del usuario
            2. Verificar si la base de datos local está vacia
            3. Si está vacia hacer la conexion a la base de datos MySQL y llenar la base de datos local
            4. Verificar la última actualizacion a la base de datos MySQL, tiene que ser menor a una semana
            si es mayor a una semana
            5. Si la última conexion es mayor a una semana, obtener todos los datos de la base de datos y meterlos en la base de daos locar
            6. Cerrar conexión a la base de datos MySQL
            7. Iniciar programa
            8. Utilizar la base de datos local
            */
            System.out.println("Hay conexion a internet");
        }else{
            /*
            1. Indicar al usuario que no posee conexion a internet
            2. Solicitar inicio de sesión del usuario
            3. Verificar si la base local está vacia
            4. Si está vacia, recordarle al usuario que necesita revisar la conexion a internet
            5. Verificar la última conexion a la base de datos MySQL
            6. Si es mayor a una semana, recordarle al usuario que necesita revisar la conexion
            a internet para actualizar la base de datos local
            7. Iniciar programa
            8. Utilizar base de datos local
            */
            System.out.println("Error de conexión\nNo se ha podido conectar a internet, por favor verifique su conexión a internet");
        }
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new splashScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbl_logotipo;
    private javax.swing.JProgressBar pb_barraCarga;
    private javax.swing.JPanel pnl_Fondo;
    // End of variables declaration//GEN-END:variables
}
